"""Add instructor tables and update classes table

Revision ID: 67002af3055a
Revises:
Create Date: 2025-07-21 13:33:10.742117

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67002af3055a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cell_executions", sa.Column("notebook_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "cell_executions", "notebooks", ["notebook_id"], ["id"])
    op.add_column("classes", sa.Column("instructor_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "classes", "instructors", ["instructor_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "classes", type_="foreignkey")
    op.drop_column("classes", "instructor_id")
    op.drop_constraint(None, "cell_executions", type_="foreignkey")
    op.drop_column("cell_executions", "notebook_id")
    # ### end Alembic commands ###
