services:
  instructor-dashboard:
    build:
      context: ./instructor-dashboard
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api/v1
      - REACT_APP_WS_URL=ws://localhost:8000
    depends_on:
      - fastapi
    volumes:
      - ./instructor-dashboard:/app
      - /app/node_modules

  jupyterlab:
    build:
      context: ./cell-monitor-extension
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
    environment:
      - JUPYTER_TOKEN=easy
      - CELL_MONITOR_TEST_MODE=true  # 簡単なアクセストークン。本番環境では変更してください
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ./fastapi_server
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_server:/app
    depends_on:
      - postgres
      - redis
      - influxdb

  worker:
    build:
      context: ./fastapi_server
    command: python -u worker/main.py
    volumes:
      - ./fastapi_server:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: progress_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  influxdb:
    image: influxdb:2.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: secretpassword
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: progress_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-token
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # --- 配布用パッケージビルド専用サービス ---
  extension-builder:
    build:
      context: ./cell-monitor-extension
      dockerfile: Dockerfile.build
    volumes:
      # ビルド成果物(.whl)をホストに反映させるためにマウント
      - ./cell-monitor-extension:/app
    environment:
      # 生成されるファイルの所有者をホストユーザーに合わせる
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}

volumes:
  postgres_data:
  influxdb_data:
  redis_data:
