# Use the official Node.js image as a base
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
# This is done to leverage Docker layer caching
COPY package*.json ./

# Install all dependencies (including devDependencies)
RUN npm install

# Copy the rest of the application's source code to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# The command to start the app (React development server)
CMD ["npm", "start"]
