name: CI Pipeline for JupyterLab Cell Monitor

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fastapi_server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Black formatter check
        run: black --check .

      - name: Run Flake8 linter
        run: flake8 .

  e2e-test:
    runs-on: ubuntu-latest
    needs: lint # Run only after linting passes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start services with Docker Compose
        run: docker compose up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start..."
          timeout 120s bash -c 'while ! curl -s -f http://localhost:8000/docs > /dev/null; do echo "Waiting for FastAPI..."; sleep 5; done'
          echo "FastAPI is ready!"
          timeout 120s bash -c 'while ! curl -s -f -L http://localhost:8888/lab > /dev/null; do echo "Waiting for JupyterLab..."; sleep 5; done'
          echo "JupyterLab is ready!"

      - name: Run E2E test
        run: |
          echo "Running E2E test..."
          docker compose exec fastapi python -m tests.e2e.test_main_flow

      - name: Stop services
        if: always() # Run whether tests succeed or fail
        run: docker compose down
